[project]
name = "tcr-assistant"
version = "0.1.0"
description = "AI assistant for TCR"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dspy",
    "google-generativeai",
    "coverage"
]

[tool.setuptools.packages.find]
where = ["."]
